### PR TITLE
Created a website

### PR DESCRIPTION
**Pull request by Evanator05**
Made a small website for the PicoTracker, im not great with css so it's definitely has lots of work that needs to be done.

### CODE REVIEW

**Comment by democloid** [comment]
Is there any screenshot of how this looks like? I'm honestly unlikely to implement this as I'm working on something myself, thou it may take me some time.

**Comment by maks** [comment]
I think the best thing to do would be to add a Github action to build the static html files from the source markdown, that would then make it easy to see the resulting html site. I'll have a crack at doing this soon.

**Comment by maks** [comment]
Im working on adding generating this as GH Pages in the Actions CI including regenerating manual from existing markdown, but in meantime @democloid here is what it looks like in Firefox:

image

image

**Comment by democloid** [comment]
I'm honestly not interested in this. What are we trying to address with this exactly?

**Comment by maks** [comment]
For me the main goal is to publish a HTML version of the manual on a stand alone page instead of making people read the markdown preview when you navigate to the markdown file inside the GitHub repo itself along with the nice buttons that can link to both the latest release and latest CI main branch "experimental" build.

**Comment by maks** [comment]
We now have a website and documentation will be done separately in the future.

**Pull request closed without merging**
