### PR TITLE
basic progress indicator during sample import

### PR DESCRIPTION
**Pull request by maks**
Shows a very basic count down of bytes remaining to be imported during sample file import into flash.

Fixes: #147

### CODE REVIEW

**Review by maks — COMMENTED** [review]
This really needs at the very least better formatting, at the moment the filename truncation is commetned out  but I think it should be used along with showing byte count down on new line.

**Comment by maks** [comment]
I'm seeing occasional crashes which I can't reliably reproduce in test, but I need to check if this is due to the outstanding clock bug, a failing sdcard or actual issue with this PR.

**Comment by democloid** [comment]
I'll test this later, but I'm tempted to think that the fact that this works is actually a problem and we should fix that, or really understand why this works to ensure it doesn't cause any issues.

My concern is that there should be no reads from flash while writing into it, so nothing should happen until we finish writing.

**Comment by maks** [comment]
> I'll test this later, but I'm tempted to think that the fact that this works is actually a problem and we should fix that, or really understand why this works to ensure it doesn't cause any issues.
> 
> My concern is that there should be no reads from flash while writing into it, so nothing should happen until we finish writing.

I mentioned this in #151 as well, but this doesnt mean that there are any reads from flash while writing it. What my code displays is actually the part of the import process where the sample is copied from `samplelib` location to the projectdir and that seems to be the longer part of the process whereas loading the sample data from the projectdir into flash, likely due to the way the current code writes to the sdcard in small chunks which is quite slow on sdcards.

So I guess this is more accurately at the moment only showing the copy process progress, but I'll improve it to show more messages just before flash load starts but the it won't be able to show progress as you mention unless perhaps we did a better way of managing flash writes by not disabling interrupts during that process on both cores.

**Comment by maks** [comment]
obsolete

**Pull request closed without merging**
