### PR TITLE
[NOT URGENT] Fixes namespace conflicts with SDLApplication

### PR DESCRIPTION
**Pull request by shockdesign**
Fixes the namespace conflict with SDLApplication on the OSX build.. just a small change really and doesn't affect much other than a warning..

### CODE REVIEW

**Comment by democloid** [comment]
Can you explain what the conflict is? it's not clear what's the problem

**Comment by shockdesign** [comment]
> Can you explain what the conflict is? it's not clear what's the problem

I know we're not really supporting other platforms, but with the OSX application, when you run it, it will throw an error about a class conflict with SDLApplication being implemented in two places. The app and the SDL Lib..

```
./lgpt
objc[71154]: Class SDLApplication is implemented in both /Users/development/Source/personal/picoTracker/projects/lgpt (0x106ca6338) and /usr/local/Cellar/sdl2/2.28.5/lib/libSDL2-2.0.0.dylib (0x1076fc998). One of the two will be used. Which one is undefined.
```

This just gives our SDLApplication a different namespace to avoid conflict and doesn't seem to have any side effects..

**Review by maks — CHANGES_REQUESTED** [review]
@shockdesign sorry I forgot about this PR. Just one small suggestion: maybe name it `MacSDL1Applcation` as that describes more what this class is.

**Comment by maks** [comment]
I'll close this out since as of #219 we no longer support SDL in the picoTracker codebase.

**Pull request closed without merging**
